version: '3.7'
services:
  migration:
    build:
      context: .
    image: migration-dev:latest
    volumes:
      - .:/go/src/github.com/rbone/migration
    links:
      - mysqldb
    environment:
      - PORT=3000
      - DATABASE_DSN=root:migration-dev-password@tcp(mysqldb)/?parseTime=true&collation=utf8mb4_unicode_520_ci

  mysqldb:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=migration-dev-password
